# Generated by Django 5.0.6 on 2024-06-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0003_alter_borrowing_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="fine_payment_status",
            field=models.CharField(default="pending", max_length=20, null=True),
        ),
    ]
